#!/usr/bin/env python3
"""Generate a self-contained badge pixel-art carousel from the icon PNGs.

The Badge IDE has no documented way to add several arbitrary binary images.
This generator downsamples each 42x42 source PNG to a 14x14 logical grid and
embeds compact palette/index data directly in badge/display-test/main.lua.
The badge app draws one reusable grid of 196 badge.ui.box widgets.
"""

from pathlib import Path

from PIL import Image


HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parent.parent / "display-test" / "main.lua"
GRID_SIZE = 14

ICONS = [
    ("BUN - TOP", "ing_bun_top.png"),
    ("BUN - BOTTOM", "ing_bun_bottom.png"),
    ("CHEESE", "ing_cheese.png"),
    ("CHEESE - CHOPPED", "ing_cheese_chopped.png"),
    ("LETTUCE", "ing_lettuce.png"),
    ("LETTUCE - CHOPPED", "ing_lettuce_chopped.png"),
    ("MEAT - RAW", "ing_meat.png"),
    ("MEAT - CHOPPED", "ing_meat_chopped.png"),
    ("MEAT - COOKED", "ing_meat_cooked.png"),
    ("PLATE", "station_plate.png"),
]


def encode_icon(label: str, filename: str) -> str:
    path = HERE / filename
    if not path.is_file():
        raise FileNotFoundError(path)

    image = Image.open(path).convert("RGBA")
    image = image.resize((GRID_SIZE, GRID_SIZE), Image.Resampling.NEAREST)

    palette: list[tuple[int, int, int]] = []
    palette_index: dict[tuple[int, int, int], int] = {}
    pixels: list[str] = []

    for r, g, b, alpha in image.getdata():
        if alpha < 128:
            pixels.append("0")
            continue

        color = (r, g, b)
        index = palette_index.get(color)
        if index is None:
            index = len(palette) + 1
            if index > 9:
                raise ValueError(
                    f"{filename} has more than 9 opaque colors after downsampling"
                )
            palette.append(color)
            palette_index[color] = index
        pixels.append(str(index))

    if len(pixels) != GRID_SIZE * GRID_SIZE:
        raise AssertionError(f"unexpected pixel count for {filename}")

    colors = ", ".join(f"0x{r:02x}{g:02x}{b:02x}" for r, g, b in palette)
    encoded = "".join(pixels)
    return (
        f'  {{ name = "{label}", source = "{filename}",\n'
        f"    palette = {{ {colors} }},\n"
        f"    pixels = [=[{encoded}]=] }},"
    )


def build_main() -> str:
    icon_data = "\n".join(encode_icon(label, filename) for label, filename in ICONS)
    return f'''-- GENERATED by badge/assets/icons/generate_lua_carousel.py.
-- Edit the PNG sources or generator, then regenerate; do not hand-edit icon data.
--
-- Controls: A = next icon, B = previous icon, HOME = exit.

local GRID = {GRID_SIZE}
local CELL = 6
local GRID_X = 118
local GRID_Y = 78
local CELL_COUNT = GRID * GRID
local BUILD_PER_TICK = 8
local PAINT_PER_TICK = 16

local icons = {{
{icon_data}
}}

local root_widget
local header
local name_label
local status_label
local cells = {{}}
local built = 0
local current = 1
local paint_at = nil
local ready = false

local function set_header(status)
  header:set_text(string.format("ASSET %d / %d", current, #icons))
  name_label:set_text(icons[current].name)
  status_label:set_text(status)
end

local function queue_paint()
  ready = false
  paint_at = 1
  set_header("Drawing...")
end

local function build_cell(index)
  local zero = index - 1
  local col = zero % GRID
  local row = math.floor(zero / GRID)
  cells[index] = badge.ui.box({{
    parent = root_widget,
    x = GRID_X + col * CELL,
    y = GRID_Y + row * CELL,
    w = CELL,
    h = CELL,
    hidden = true,
    clickable = false,
    bg_color = 0xffffff,
    bg_opa = 255,
    border_width = 0,
    radius = 0,
    pad_all = 0,
  }})
end

local function paint_cell(index)
  local icon = icons[current]
  local palette_index = string.byte(icon.pixels, index) - string.byte("0")
  local cell = cells[index]

  if palette_index == 0 then
    cell:hidden(true)
  else
    cell:set_color(icon.palette[palette_index])
    cell:hidden(false)
  end
end

function on_enter(root)
  root_widget = root

  header = badge.ui.label(root, "ASSET CAROUSEL")
  header:set_font_size("large")
  header:align("top_mid", 0, 10)

  name_label = badge.ui.label(root, "")
  name_label:style({{ text_font = 16, text_align = "center" }})
  name_label:align("top_mid", 0, 43)

  status_label = badge.ui.label(root, "Building pixel grid...")
  status_label:style({{ text_font = 14, text_color = 0xaaaaaa }})
  status_label:align("bottom_mid", 0, -34)

  local controls = badge.ui.label(root, "A: next   B: previous   HOME: exit")
  controls:style({{ text_font = 14 }})
  controls:align("bottom_mid", 0, -10)

  badge.led.clear()
  badge.led.set_all(0, 20, 40)
  badge.led.show()
end

function on_tick()
  if built < CELL_COUNT then
    local stop = math.min(built + BUILD_PER_TICK, CELL_COUNT)
    while built < stop do
      built = built + 1
      build_cell(built)
    end
    status_label:set_text(string.format("Loading %d%%", math.floor(built * 100 / CELL_COUNT)))
    if built == CELL_COUNT then queue_paint() end
    return
  end

  if paint_at then
    local stop = math.min(paint_at + PAINT_PER_TICK - 1, CELL_COUNT)
    while paint_at <= stop do
      paint_cell(paint_at)
      paint_at = paint_at + 1
    end
    if paint_at > CELL_COUNT then
      paint_at = nil
      ready = true
      set_header(icons[current].source)
    end
  end
end

function on_button(button, kind)
  if kind ~= badge.input.KIND.PRESSED or not ready then return end
  local B = badge.input.BUTTON

  if button == B.A then
    current = (current % #icons) + 1
    queue_paint()
  elseif button == B.B then
    current = ((current - 2) % #icons) + 1
    queue_paint()
  end
end

function on_exit()
  badge.led.clear()
  badge.led.show()
end
'''


def main() -> None:
    source = build_main()
    OUTPUT.write_text(source, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT}")
    print(f"Embedded {len(ICONS)} icons; main.lua is {len(source.encode('utf-8'))} bytes")


if __name__ == "__main__":
    main()
