import {
  canRunAction,
  formatSeconds,
  healthStatus,
  isStale,
  progressPercent,
  trackingCoverage,
  GAME_ACTIONS,
  SETUP_PHASES,
} from "./state.js";

const escapeHtml = (value) => String(value ?? "")
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&#039;");
const escapeAttr = escapeHtml;
const upper = (value) => String(value || "").replaceAll("-", " ").toUpperCase();
const finite = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const clamp = (value, min = 0, max = 100) => Math.max(min, Math.min(max, finite(value, min)));

function phaseLabel(phase) {
  if (phase === SETUP_PHASES.SCANNING) return "SCANNING ROOM";
  if (phase === SETUP_PHASES.LAYOUT_PROPOSED) return "PROPOSED FLOOR PLAN";
  if (phase === SETUP_PHASES.BURGER_PLACEMENT) return "BURGER LEVEL PLACEMENT";
  if (phase === SETUP_PHASES.LAYOUT_ACCEPTED) return "BURGER LEVEL READY";
  if (phase === SETUP_PHASES.RUNNING) return "BURGER GAME RUNNING";
  if (phase === SETUP_PHASES.ENDED) return "GAME ENDED";
  return "HOST IDLE";
}

function statusPill(status, label = status) {
  const normalized = String(status || "unknown").toLowerCase();
  return `<span class="status-pill status-${escapeAttr(normalized)}"><span class="status-dot" aria-hidden="true"></span>${escapeHtml(upper(label))}</span>`;
}

function commandButton(state, action, label) {
  const disabled = !canRunAction(state, action) ? " disabled" : "";
  return `<button class="control-button" type="button" data-command="${escapeAttr(action)}"${disabled}>${escapeHtml(label)}</button>`;
}

function renderHostPanel(state) {
  const setup = state.setup || {};
  return `<section class="host-panel panel" aria-labelledby="host-title">
    <div class="host-copy">
      <p class="eyebrow">HOST MODE / LEVEL SETUP</p>
      <h2 id="host-title">${escapeHtml(phaseLabel(setup.phase))}</h2>
      <p class="muted">${escapeHtml(setup.message || "The master Pi owns setup and game state.")}</p>
    </div>
    <div class="setup-controls" aria-label="Host controls">
      ${commandButton(state, GAME_ACTIONS.START_HOST, "Start")}
      ${commandButton(state, GAME_ACTIONS.SCAN_ROOM, "Scan Room")}
      ${commandButton(state, GAME_ACTIONS.APPROVE_LAYOUT, "Approve Layout")}
      ${commandButton(state, GAME_ACTIONS.RESCAN, "Rescan")}
      ${commandButton(state, GAME_ACTIONS.START_GAME, "Start Game")}
      ${commandButton(state, GAME_ACTIONS.END_GAME, "End Game")}
      ${commandButton(state, GAME_ACTIONS.RESET_GAME, "Reset Game")}
    </div>
  </section>`;
}

function mapStyle(item) {
  return `left:${clamp(item.x, 0, 100)}%;top:${clamp(item.y, 0, 100)}%;width:${clamp(item.width, 1, 100)}%;height:${clamp(item.height, 1, 100)}%;`;
}

function renderFloorPlan(state, now) {
  const plan = state.floorPlan || {};
  const accepted = plan.accepted === true;
  const walls = (plan.walls || []).map((wall, index) => `<div class="map-wall" style="${mapStyle(wall)}" aria-hidden="true" data-wall="${index}"></div>`).join("");
  const stations = (plan.stations || []).map((station) => `<div class="map-station station-${escapeAttr(station.kind || "generic")}" style="${mapStyle(station)}" data-station="${escapeAttr(station.id)}"><strong>${escapeHtml(station.label || station.id)}</strong></div>`).join("");
  return `<section class="map-panel panel" aria-labelledby="map-title">
    <div class="section-heading"><div><p class="eyebrow">ROOM MIRROR</p><h2 id="map-title">${accepted ? "Accepted burger floor plan" : "Proposed room floor plan"}</h2></div>${statusPill(accepted ? "healthy" : "degraded", accepted ? "authoritative layout" : "awaiting approval")}</div>
    <div class="floor-plan ${accepted ? "is-accepted" : "is-proposed"}" role="img" aria-label="${accepted ? "Accepted burger" : "Proposed room"} top-down station floor plan">
      <div class="map-grid" aria-hidden="true"></div>${walls}${stations}
      ${accepted ? "" : "<div class=\"map-overlay\">APPROVE FLOOR PLAN TO GENERATE BURGER LEVEL</div>"}
    </div>
    <div class="map-legend" aria-label="Floor plan legend"><span>Stations and walls are generated by the Pi</span></div>
  </section>`;
}

function renderPlayers(state, now) {
  const players = state.players || [];
  return `<section class="players-panel panel" aria-labelledby="players-title"><div class="section-heading"><div><p class="eyebrow">FIXED BADGE CREW</p><h2 id="players-title">Three players</h2></div><span class="muted">Held items and actions from master Pi</span></div><div class="player-roster">${players.length ? players.map((player) => {
    const stale = isStale(player, now);
    const trackingText = stale ? "SIGNAL STALE" : "CONNECTED";
    const held = player.heldItem || (player.inventory?.length ? player.inventory.join(", ") : "EMPTY HANDS");
    const label = `${player.name || player.label || player.id}, holding ${held}, ${player.actionState || "READY"}`;
    return `<article class="player-card player-${escapeAttr(player.color || player.id)}${stale ? " is-stale" : ""}" data-player="${escapeAttr(player.id)}" data-stale="${stale}" aria-label="${escapeAttr(label)}"><div class="player-badge">${escapeHtml(player.label || player.id)}</div><div><h3>${escapeHtml(player.name || "PLAYER")}</h3><p class="player-holding">Holding: <strong>${escapeHtml(held)}</strong></p><p class="player-action">${escapeHtml(player.actionState || "READY")} · ${trackingText}</p></div></article>`;
  }).join("") : "<p class=\"muted\">Waiting for the three fixed player snapshots.</p>"}</div></section>`;
}

function renderBurgerPlacement(state) {
  const level = state.burgerLevel;
  if (!level || level.status === "not-generated") return "";
  const instructions = level.placementInstructions || [];
  return `<section class="placement-panel panel" aria-labelledby="placement-title">
    <div class="section-heading"><div><p class="eyebrow">BURGER LEVEL</p><h2 id="placement-title">Place the physical level</h2></div>${statusPill(level.status, level.status)}</div>
    <p class="muted">The approved room scan generated these locations. Place the printed ingredient icons, stationary boards, stoves, and serving badge before starting.</p>
    <ul class="placement-list">${instructions.map((item) => `<li><strong>${escapeHtml(item.label)}</strong><span>${escapeHtml(item.instruction)}</span></li>`).join("")}</ul>
  </section>`;
}

function renderOrderCard(order, index) {
  const components = (order.components || []).map((item) => `<li>${escapeHtml(item)}</li>`).join("");
  const toppings = (order.toppings || []).map((item) => `<span class="topping-chip">${escapeHtml(item)}</span>`).join("");
  const segments = order.patienceSegments || [];
  const meter = [0, 1, 2].map((segment) => `<span class="patience-segment patience-${escapeAttr(segments[segment] || "unknown")}" aria-label="Patience segment ${segment + 1} ${escapeAttr(segments[segment] || "unknown")}"></span>`).join("");
  return `<article class="order-card" data-order="${escapeAttr(order.id || index)}"><div class="section-heading"><div><p class="eyebrow">ACTIVE ORDER ${index + 1}</p><h3>${escapeHtml(order.recipe || order.dish || "BURGER")}</h3></div>${statusPill(order.status === "active" ? "healthy" : order.status, order.status)}</div><div class="order-timer"><span class="eyebrow">PATIENCE / COUNTDOWN</span><strong>${escapeHtml(formatSeconds(order.remainingSeconds))}</strong></div><div class="patience-meter" aria-label="Three-segment order patience">${meter}</div><p class="eyebrow">RECIPE INGREDIENTS</p><div class="topping-list">${toppings || "<span class=\"muted\">MEAT ONLY</span>"}</div><ul class="ingredient-list">${components}</ul></article>`;
}

function renderOrder(state) {
  const orders = state.orders || (state.order ? [state.order] : []);
  return `<section class="order-panel panel" aria-labelledby="order-title"><div class="section-heading"><div><p class="eyebrow">ACTIVE ORDERS</p><h2 id="order-title">${orders.length} burger ${orders.length === 1 ? "order" : "orders"}</h2></div><span class="muted">One card per burger</span></div>${orders.length ? `<div class="order-list">${orders.map(renderOrderCard).join("")}</div>` : "<p class=\"muted\">Waiting for an order from the master Pi.</p>"}</section>`;
}

function renderScoreAndClock(state) {
  const score = state.score || {};
  const clock = state.clock || {};
  return `<section class="score-panel panel" aria-labelledby="score-title"><p class="eyebrow">ROUND ECONOMY</p><div class="economy-values"><div><span class="eyebrow">GOLD</span><strong id="score-title" class="score-value">${escapeHtml(score.gold ?? score.value ?? 0)}</strong></div><div class="tip-value"><span class="eyebrow">TIPS</span><strong>${escapeHtml(score.tips ?? 0)}</strong></div></div><p class="muted">${escapeHtml(score.delivered ?? 0)} burgers served</p><div class="round-clock"><span class="eyebrow">HOST-OWNED TIMER / TWO-MINUTE ROUND</span><strong>${escapeHtml(formatSeconds(clock.remainingSeconds))}</strong>${statusPill(clock.status || "unknown", clock.status || "unknown")}</div></section>`;
}

function renderStations(state) {
  const stations = state.stations || [];
  return `<section class="stations-panel panel" aria-labelledby="stations-title"><div class="section-heading"><div><p class="eyebrow">AUTHORITATIVE STATION STATE</p><h2 id="stations-title">Cut, cook &amp; assemble</h2></div></div><div class="station-list">${stations.length ? stations.map((station) => {
    const progress = progressPercent(station.progress);
    return `<article class="station-card station-${escapeAttr(station.kind || "generic")}"><div class="station-title"><h3>${escapeHtml(station.label || station.id)}</h3>${statusPill(station.status || "unknown", station.status || "unknown")}</div><p class="station-item">${escapeHtml(station.item || "EMPTY")}</p><div class="progress-track" role="progressbar" aria-label="${escapeAttr(station.label || station.id)} progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress.toFixed(0)}"><span style="width:${progress.toFixed(2)}%"></span></div><div class="station-meta"><span>${progress.toFixed(0)}%</span><span>${station.remainingSeconds == null ? "--:--" : `${escapeHtml(formatSeconds(station.remainingSeconds))} remaining`}</span></div></article>`;
  }).join("") : "<p class=\"muted\">No station state received.</p>"}</div></section>`;
}

function renderServing(state) {
  const serving = state.serving || {};
  const event = serving.lastEvent;
  const submission = state.submission || {};
  const queue = Math.max(0, Number(serving.gooseQueue || 0));
  const geese = Array.from({ length: Math.min(queue, 8) }, (_, index) => `<span class="goose-token" aria-label="Waterloo goose ${index + 1}">GOOSE</span>`).join("");
  if (!event && submission.status === "idle") return `<section class="delivery-panel serving-panel panel" aria-labelledby="serving-title"><p class="eyebrow">SUBMISSION / SERVING BADGE</p><h2 id="serving-title">Ready for the three-player shake</h2><div class="goose-queue" aria-label="${queue} Waterloo geese waiting in line">${geese}</div><p class="muted">${escapeHtml(submission.detail || "The master Pi decides whether the submitted plate matches the active order.")}</p></section>`;
  const outcome = event || submission;
  const success = outcome.status === "success";
  return `<section class="delivery-panel serving-panel panel delivery-${success ? "success" : "failure"}" aria-labelledby="serving-title" role="status"><p class="eyebrow">SUBMISSION RESULT / ${queue} GEESE WAITING</p><h2 id="serving-title">${escapeHtml(outcome.message || (success ? "BURGER SERVED" : "SUBMISSION REJECTED"))}</h2><p>${escapeHtml(outcome.detail || "")}</p><div class="submission-values"><strong class="delivery-points">${success ? `+${escapeHtml(outcome.points ?? outcome.gold ?? 0)} GOLD` : "PENALTY APPLIED"}</strong><span>${success ? `+${escapeHtml(outcome.tip ?? 0)} TIP` : "NO TIP"}</span></div></section>`;
}

function renderHealthItem(item, now) {
  const status = healthStatus(item, now);
  return `<li class="health-item health-${escapeAttr(status)}"><span class="health-indicator" aria-hidden="true"></span><span><strong>${escapeHtml(item.label || item.id || "SYSTEM")}</strong><small>${escapeHtml(item.detail || "")}</small></span><span class="health-label">${escapeHtml(upper(status))}</span></li>`;
}

function renderHealth(state, now) {
  const health = state.health || {};
  const workers = health.workers || health.cameras || [];
  const coverage = trackingCoverage(state, now);
  return `<section class="health-panel panel" aria-labelledby="health-title"><div class="section-heading"><div><p class="eyebrow">LOCAL SYSTEM HEALTH</p><h2 id="health-title">Gateway &amp; camera health</h2></div>${statusPill(coverage, `tracking ${coverage}`)}</div><ul class="health-list">${health.gateway ? renderHealthItem(health.gateway, now) : ""}${workers.map((worker) => renderHealthItem(worker, now)).join("")}${health.inference ? renderHealthItem(health.inference, now) : ""}</ul><p class="health-callout ${coverage === "degraded" ? "is-degraded" : ""}">${coverage === "degraded" ? "TRACKING DEGRADED — stale worker data is marked; the burger game is continuing." : "TRACKING COVERAGE HEALTHY"}</p></section>`;
}

export function renderApp(state, now = Date.now(), connectionError = "") {
  if (!state) return `<section class="loading-card"><p class="eyebrow">HTN26 / BURGER LEVEL</p><h1>Waiting for authoritative state…</h1><p class="muted">No game state has been received from the local transport.</p>${connectionError ? `<div id="ui-error" class="ui-error" role="alert">${escapeHtml(connectionError)}</div>` : ""}</section>`;
  return `<div class="app-shell"><header class="topbar"><div><p class="eyebrow">HTN26 / OVERCOOKED IRL</p><h1>Burger Level Control</h1></div><div class="connection-summary" role="status"><span class="connection-light"></span><span>LOCAL MASTER PI</span><small>${escapeHtml(state.source || "authoritative state")}</small></div></header>${connectionError ? `<div id="ui-error" class="ui-error" role="alert">${escapeHtml(connectionError)}</div>` : ""}${renderHostPanel(state)}<div class="primary-grid">${renderFloorPlan(state, now)}<div class="side-stack">${renderOrder(state)}${renderScoreAndClock(state)}</div></div>${renderPlayers(state, now)}<div class="secondary-grid">${renderStations(state)}${renderServing(state)}</div>${renderBurgerPlacement(state)}${renderHealth(state, now)}<footer class="footer-note">Floor plans, players, holdings, timers, orders, economy, station state, health, and submission results are snapshots from the master Pi. This UI never simulates gameplay.</footer></div>`;
}
