-- GENERATED by badge/assets/icons/generate_lua_carousel.py.
-- Edit the PNG sources or generator, then regenerate; do not hand-edit icon data.
--
-- Controls: A = next icon, B = previous icon, HOME = exit.

local GRID = 14
local CELL = 6
local GRID_X = 118
local GRID_Y = 78
local CELL_COUNT = GRID * GRID
local BUILD_PER_TICK = 8
local PAINT_PER_TICK = 16

local icons = {
  { name = "BUN - TOP", source = "ing_bun_top.png",
    palette = { 0x6b3a16, 0xf1c98a, 0xc8883f },
    pixels = [=[0000000000000000000000000000000000000000000000111111000000122233333100003323333233000133333333331001333333333310003333333333000011111111110000001111110000000000000000000000000000000000000000000000]=] },
  { name = "BUN - BOTTOM", source = "ing_bun_bottom.png",
    palette = { 0xf1c98a, 0x6b3a16, 0xc8883f },
    pixels = [=[0000000000000000000000000000000000000000000000000000000000000000000000001111111111000233333333332002333333333320022222222222200022222222220000000000000000000000000000000000000000000000000000000000]=] },
  { name = "CHEESE", source = "ing_cheese.png",
    palette = { 0x9a6b0c, 0xf9e07a, 0xc08a12, 0xe8b21f },
    pixels = [=[0000000000000000000010000000000012210210000000222222200000012233222100000222222221000014444444410000443344333100014444443331000014344444410000043411444000000010001110000000000000000000000000000000]=] },
  { name = "CHEESE - CHOPPED", source = "ing_cheese_chopped.png",
    palette = { 0xf9e07a, 0x9a6b0c, 0xe8b21f },
    pixels = [=[0000000000000000000000000000000000000000000000000000000000000000000000001111111111200233333333332002333333333320022222222222000000000000000000000000000000000000000000000000000000000000000000000000]=] },
  { name = "LETTUCE", source = "ing_lettuce.png",
    palette = { 0x24571f, 0x4a9b33, 0x8ed14e },
    pixels = [=[0000000000000000000000000000000001111000000011122221110000222222222200002322322222000013223112210000222222122200002221222122000012222222210000012222221000000011221100000000000000000000000000000000]=] },
  { name = "LETTUCE - CHOPPED", source = "ing_lettuce_chopped.png",
    palette = { 0x24571f, 0x8ed14e, 0x4a9b33, 0xd7ef9a },
    pixels = [=[0000000000000000000000000000000110000110000023330023330001332311332310003233333233000011343333110003333334333230132333233332311332133331323101330311203210000013333100000000033320000000000000000000]=] },
  { name = "MEAT - RAW", source = "ing_meat.png",
    palette = { 0x4e1a17, 0xe9b9ae, 0x7e2620, 0xb0342a, 0xd9695a },
    pixels = [=[0000000000000000000000000000000000000000000001222222100000234444443200013444444443100134242424531001324244244310013444442443100023444444320000012222221000000000000000000000000000000000000000000000]=] },
  { name = "MEAT - CHOPPED", source = "ing_meat_chopped.png",
    palette = { 0x661f1b, 0xb0342a, 0xd9695a },
    pixels = [=[0000000000000000000000000000000000000000000000000000000000122222222100002222233322000122222222221001222222222210002223332222000012222222210000001111110000000000000000000000000000000000000000000000]=] },
  { name = "MEAT - COOKED", source = "ing_meat_cooked.png",
    palette = { 0x661f1b, 0x7a4526, 0xa9693a },
    pixels = [=[0000000000000000000000000000000000000000000000000000000000122222222100002333333332000122222222221001222222222210002222222222000012222222210000001111110000000000000000000000000000000000000000000000]=] },
  { name = "PLATE", source = "station_plate.png",
    palette = { 0xc2c9d4, 0x333a45, 0x6e7784 },
    pixels = [=[0000000000000000000000000000000000000000000000000000000000000000000000000111111110000011111111110002131111113120021311111131200011133331110000211111111200000022222200000000000000000000000000000000]=] },
}

local root_widget
local header
local name_label
local status_label
local cells = {}
local built = 0
local current = 1
local paint_at = nil
local ready = false

local function set_header(status)
  header:set_text(string.format("ASSET %d / %d", current, #icons))
  name_label:set_text(icons[current].name)
  status_label:set_text(status)
end

local function queue_paint()
  ready = false
  paint_at = 1
  set_header("Drawing...")
end

local function build_cell(index)
  local zero = index - 1
  local col = zero % GRID
  local row = math.floor(zero / GRID)
  cells[index] = badge.ui.box({
    parent = root_widget,
    x = GRID_X + col * CELL,
    y = GRID_Y + row * CELL,
    w = CELL,
    h = CELL,
    hidden = true,
    clickable = false,
    bg_color = 0xffffff,
    bg_opa = 255,
    border_width = 0,
    radius = 0,
    pad_all = 0,
  })
end

local function paint_cell(index)
  local icon = icons[current]
  local palette_index = string.byte(icon.pixels, index) - string.byte("0")
  local cell = cells[index]

  if palette_index == 0 then
    cell:hidden(true)
  else
    cell:set_color(icon.palette[palette_index])
    cell:hidden(false)
  end
end

function on_enter(root)
  root_widget = root

  header = badge.ui.label(root, "ASSET CAROUSEL")
  header:set_font_size("large")
  header:align("top_mid", 0, 10)

  name_label = badge.ui.label(root, "")
  name_label:style({ text_font = 16, text_align = "center" })
  name_label:align("top_mid", 0, 43)

  status_label = badge.ui.label(root, "Building pixel grid...")
  status_label:style({ text_font = 14, text_color = 0xaaaaaa })
  status_label:align("bottom_mid", 0, -34)

  local controls = badge.ui.label(root, "A: next   B: previous   HOME: exit")
  controls:style({ text_font = 14 })
  controls:align("bottom_mid", 0, -10)

  badge.led.clear()
  badge.led.set_all(0, 20, 40)
  badge.led.show()
end

function on_tick()
  if built < CELL_COUNT then
    local stop = math.min(built + BUILD_PER_TICK, CELL_COUNT)
    while built < stop do
      built = built + 1
      build_cell(built)
    end
    status_label:set_text(string.format("Loading %d%%", math.floor(built * 100 / CELL_COUNT)))
    if built == CELL_COUNT then queue_paint() end
    return
  end

  if paint_at then
    local stop = math.min(paint_at + PAINT_PER_TICK - 1, CELL_COUNT)
    while paint_at <= stop do
      paint_cell(paint_at)
      paint_at = paint_at + 1
    end
    if paint_at > CELL_COUNT then
      paint_at = nil
      ready = true
      set_header(icons[current].source)
    end
  end
end

function on_button(button, kind)
  if kind ~= badge.input.KIND.PRESSED or not ready then return end
  local B = badge.input.BUTTON

  if button == B.A then
    current = (current % #icons) + 1
    queue_paint()
  elseif button == B.B then
    current = ((current - 2) % #icons) + 1
    queue_paint()
  end
end

function on_exit()
  badge.led.clear()
  badge.led.show()
end
